version: '3.8'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./swagger.json:/src/swagger/swagger.json
    environment:
      - SWAGGER_JSON=/src/swagger/swagger.json
    restart: unless-stopped
